/**
 * @file    autoconf.h
 * @brief   Header file for buffer configuration
 * @author  Auto-generated
 * @date    29/09/2025
 *
 * @copyright Copyright (c) TOLOSAT 2025
 */

#ifndef AUTOCONF_H
#define AUTOCONF_H

#define CONFIG_CONFIG_NAME "art_pi"
#define CONFIG_BOARD_ART_PI y
// CONFIG_BOARD_KLARA is not set
// CONFIG_BOARD_QEMU is not set
// CONFIG_BOARD_NUCLEO_H745ZI is not set
// CONFIG_BOARD_NUCLEO_F411RE is not set
#define CONFIG_BOARD_NAME "ART_PI"
#define CONFIG_CHIP_VENDOR "ST"
#define CONFIG_CHIP_FAMILLY "STM32H7"
#define CONFIG_CHIP "STM32H750xx"
#define CONFIG_ARCH "cortex-m7"
// CONFIG_DUAL_CORE is not set
#define CONFIG_HAS_LOAD_MEMORY_RAM y
// CONFIG_HAS_LOAD_MEMORY_FLASH is not set
#define CONFIG_HAS_FPU y
#define CONFIG_FPU_TYPE "fpv5-d16"
#define CONFIG_HAS_CACHE y
#define CONFIG_HAS_MPU y
#define CONFIG_HAS_WDG y
#define CONFIG_HAS_ECC y
// CONFIG_HAS_SPISD_MEMORY is not set
#define CONFIG_HAS_SD_MEMORY y
#define CONFIG_HAS_RAM_MEMORY y
// CONFIG_HAS_FMC_NAND_MEMORY is not set
#define CONFIG_HAS_QSPI_NOR_MEMORY y
// CONFIG_HAS_QSPI_MRAM_MEMORY is not set
#define CONFIG_HAS_USB_OTG y
#define CONFIG_HAS_INVERTED_SYSLED_LOGIC y
#define CONFIG_LOAD_MEMORY_RAM y
#define CONFIG_FPU y
#define CONFIG_CACHE y
#define CONFIG_MPU y
// CONFIG_WDG is not set
// CONFIG_ECC is not set
#define CONFIG_KERNEL_TICK_FREQ 1000
#define CONFIG_KERNEL_PREEMPTIVE y
#define CONFIG_KERNEL_SCHED_FIFO y
// CONFIG_KERNEL_SCHED_ROUND_ROBIN is not set
#define CONFIG_MAX_NB_TASKS 16
#define CONFIG_MAX_NB_MUTEXES 16
#define CONFIG_MAX_NB_BUFFERS 32
#define CONFIG_MAX_NB_TIMERS 16
#define CONFIG_MAX_NB_FILES 16
#define CONFIG_MAX_NB_PERIPHERALS 8
#define CONFIG_MAX_NB_MEMORIES 8
#define CONFIG_MAX_NB_HKS 64
#define CONFIG_MAX_NB_DEVICES 128
#define CONFIG_FS_ENABLED y
#define CONFIG_CONTEXT_ENABLED y
// CONFIG_CONSOLE_NONE is not set
// CONFIG_CONSOLE_UART is not set
// CONFIG_CONSOLE_ITM is not set
#define CONFIG_CONSOLE_FILE y
// CONFIG_CONSOLE_CIRCULAR_BUFFER is not set
#define CONFIG_CONSOLE_FILE_SIZE 512
#define CONFIG_SYSWDG_PERIOD_MS 500

#endif /* AUTOCONF_H */
